# Generated by Django 3.0.9 on 2020-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_column='제목', max_length=400)),
                ('news_url', models.URLField(db_column='링크', max_length=400)),
                ('image_link', models.CharField(db_column='이미지', max_length=400)),
                ('published_date', models.DateTimeField(blank=True, db_column='등록날짜', null=True)),
            ],
            options={
                'db_table': 'article_cloud',
                'managed': True,
            },
        ),
    ]
