# Generated by Django 3.1 on 2020-08-31 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_column='제목', max_length=400)),
                ('news_url', models.URLField(db_column='링크', max_length=400)),
                ('image_link', models.CharField(db_column='이미지', max_length=400)),
                ('published_date', models.CharField(db_column='등록날짜', max_length=400)),
                ('field', models.CharField(db_column='분류', max_length=50)),
                ('news_text', models.CharField(db_column='내용', max_length=500)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
                ('contest_views', models.IntegerField(db_column='조회수')),
            ],
            options={
                'db_table': 'contest_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
                ('contest_views', models.IntegerField(db_column='조회수')),
            ],
            options={
                'db_table': 'contest_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest_science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
                ('contest_views', models.IntegerField(db_column='조회수')),
            ],
            options={
                'db_table': 'contest_science',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_column='기업명', max_length=100)),
                ('job_title', models.CharField(db_column='직무', max_length=300)),
                ('experience', models.CharField(db_column='경력사항', max_length=300)),
                ('edu_level', models.CharField(db_column='학력', max_length=50)),
                ('type', models.CharField(db_column='근무형태', max_length=50)),
                ('location', models.CharField(db_column='근무지', max_length=50)),
                ('category', models.CharField(db_column='분류', max_length=300)),
                ('link', models.CharField(db_column='상세링크', max_length=300)),
                ('field', models.CharField(db_column='분류필터', max_length=50)),
            ],
            options={
                'db_table': 'job_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_column='email', max_length=255, verbose_name='email')),
                ('username', models.CharField(db_column='username', max_length=30, unique=True)),
                ('이름', models.CharField(db_column='name', max_length=30)),
                ('휴대폰번호', models.BigIntegerField(db_column='phone')),
                ('성별', models.CharField(choices=[('여자', '여자'), ('남자', '남자')], db_column='gender', max_length=30)),
                ('관심사1', models.CharField(choices=[('빅데이터', '빅데이터'), ('인공지능', '인공지능(AI)'), ('클라우드', '클라우드'), ('DevOps', 'DevOps'), ('보안', '보안'), ('선택 안함', '선택 안함')], db_column='first_interest', max_length=30)),
                ('관심사2', models.CharField(choices=[('빅데이터', '빅데이터'), ('인공지능', '인공지능(AI)'), ('클라우드', '클라우드'), ('DevOps', 'DevOps'), ('보안', '보안'), ('선택 안함', '선택 안함')], db_column='second_interest', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('max_member', models.IntegerField(default=4)),
                ('members', models.ManyToManyField(null=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study',
            },
        ),
    ]
