# Generated by Django 3.0.5 on 2020-08-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_cloud',
        ),
        migrations.DeleteModel(
            name='News_dev',
        ),
        migrations.DeleteModel(
            name='News_new_tech',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
