# Generated by Django 3.1 on 2020-08-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
    ]
