# Generated by Django 3.1 on 2020-08-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='max_member',
            field=models.IntegerField(default=4),
        ),
    ]
