# Generated by Django 3.0.9 on 2020-08-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200812_1620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='article_new_tech',
        ),
    ]
