# Generated by Django 3.1 on 2020-08-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200819_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs_Cloud',
        ),
        migrations.DeleteModel(
            name='Jobs_DB',
        ),
        migrations.DeleteModel(
            name='Jobs_Python',
        ),
    ]
