# Generated by Django 3.1 on 2020-09-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_contest_jobs_study'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
    ]
