# Generated by Django 3.1 on 2020-08-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_study_max_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='members',
        ),
    ]
