# Generated by Django 3.1 on 2020-08-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='owner',
        ),
    ]
