# Generated by Django 3.1 on 2020-08-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200819_1631'),
        ('blog', '0002_auto_20200819_1356'),
    ]

    operations = [
    ]
