# Generated by Django 3.1 on 2020-08-30 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_study_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
