# Generated by Django 3.1 on 2020-08-28 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_study_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
