# Generated by Django 3.1 on 2020-09-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200901_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='article_likes',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_likes',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_likes',
        ),
    ]
