# Generated by Django 3.0.9 on 2020-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200814_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
            ],
            options={
                'db_table': 'contest_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
            ],
            options={
                'db_table': 'contest_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest_science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(db_column='공모이름', max_length=400)),
                ('contest_image', models.CharField(db_column='이미지', max_length=400)),
                ('contest_category', models.CharField(db_column='분야', max_length=400)),
                ('contest_participant', models.CharField(db_column='응모대상', max_length=400)),
                ('contest_organizer', models.CharField(db_column='주최/주관', max_length=400)),
                ('contest_sponsor', models.CharField(db_column='후원/협찬', max_length=400)),
                ('contest_period', models.CharField(db_column='접수기간', max_length=400)),
                ('contest_money', models.CharField(db_column='총 상금', max_length=400)),
                ('contest_firstmoney', models.CharField(db_column='1등 상금', max_length=400)),
                ('contest_homepage', models.CharField(db_column='홈페이지', max_length=400)),
                ('contest_file', models.CharField(db_column='첨부파일', max_length=400)),
            ],
            options={
                'db_table': 'contest_science',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
