# Generated by Django 3.1 on 2020-08-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_study_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='member',
        ),
    ]
