# Generated by Django 3.1 on 2020-09-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200901_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='article_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='contest_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='job_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
