# Generated by Django 3.0.9 on 2020-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200814_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_column='제목', max_length=400)),
                ('news_url', models.URLField(db_column='링크', max_length=400)),
                ('image_link', models.CharField(db_column='이미지', max_length=400)),
                ('published_date', models.CharField(db_column='등록날짜', max_length=400)),
                ('field', models.CharField(db_column='분류', max_length=50)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='news_dev',
            table='articles',
        ),
    ]
