# Generated by Django 3.1 on 2020-08-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200814_1637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs_cloud',
            table='job_list',
        ),
        migrations.AlterModelTable(
            name='jobs_db',
            table='job_list',
        ),
        migrations.AlterModelTable(
            name='jobs_python',
            table='job_list',
        ),
    ]
