# Generated by Django 3.0.5 on 2020-08-17 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200814_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_column='email', max_length=255, verbose_name='email')),
                ('username', models.CharField(db_column='username', max_length=30, unique=True)),
                ('이름', models.CharField(db_column='name', max_length=30)),
                ('휴대폰번호', models.BigIntegerField(db_column='phone')),
                ('성별', models.SmallIntegerField(choices=[(0, '여자'), (1, '남자')], db_column='gender')),
                ('관심사1', models.SmallIntegerField(choices=[(0, '빅데이터'), (1, '인공지능(AI)'), (2, '클라우드'), (3, 'DevOps'), (4, '보안'), (5, '선택 안함')], db_column='first_interest')),
                ('관심사2', models.SmallIntegerField(choices=[(0, '빅데이터'), (1, '인공지능(AI)'), (2, '클라우드'), (3, 'DevOps'), (4, '보안'), (5, '선택 안함')], db_column='second_interest')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
