# Generated by Django 3.0.5 on 2020-08-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='AUTH_USER_MODEL',
        ),
    ]
