# Generated by Django 3.1 on 2020-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articles_article_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
