# Generated by Django 3.1 on 2020-08-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200816_1315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs_python',
            table='job_python',
        ),
    ]
