# Generated by Django 3.1 on 2020-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200902_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article',
            new_name='article_user',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='contest',
            new_name='contest_user',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job',
            new_name='job_user',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
