# Generated by Django 3.0.5 on 2020-08-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200817_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='AUTH_USER',
        ),
    ]
