# Generated by Django 3.1 on 2020-08-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200816_1320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs_python',
            table='job_list',
        ),
    ]
