# Generated by Django 3.1 on 2020-09-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200902_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
