# Generated by Django 3.1 on 2020-09-23 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200924_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.PositiveIntegerField(db_column='article_like_count', default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='article_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_like_count',
            field=models.PositiveIntegerField(db_column='contest_like_count', default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='contest_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_like_count',
            field=models.PositiveIntegerField(db_column='job_like_count', default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='job_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
