# Generated by Django 3.1 on 2020-09-23 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200924_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
