# Generated by Django 3.1 on 2020-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200924_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
