# Generated by Django 3.1 on 2020-09-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200924_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.PositiveIntegerField(db_column='article_like_count', default=0),
        ),
    ]
